//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SouthCoat1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocation
    {
        public string LocationId { get; set; }
        public int MaxQuantity { get; set; }
        public string ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
